/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b6045461-3f0b-4734-abca-79a745aa45d2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ZwUhM0WC1",
    "aws_user_pools_web_client_id": "7ue9419909kpmrfjhq604r19f4",
    "oauth": {
        "domain": "cmpe17289a6d05e-89a6d05e-devenv.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
