/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:bcfbdb9a-8713-4e78-a46d-3b166f8af820",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_OaDB6jcKL",
    "aws_user_pools_web_client_id": "4nc8a0tpgdj8aucbh9n01f0uv6",
    "oauth": {
        "domain": "cmpe172506f9cfb-506f9cfb-newdevenv.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
